version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=abelarif
      - POSTGRES_PASSWORD=1325
      - POSTGRES_DB=nest
    networks:
      - ft_transcendence
networks:
  ft_transcendence: